### PR TITLE
Rewrite how API works

### PR DESCRIPTION
**Pull request by dkpat12**
Implement multi-dimensional associative arrays for wiki data. Add titles, description,  and update links to https for wikis. Implement loops on other pages to use data from api file.

### CODE REVIEW

**Comment by dkpat12** [comment]
FULL DISCLOSURE:

I haven't tested these changes. I don't have a working php server on my windows desktop .  I have tested bits of it with an online php interpreter. but please check these changes out and verify everything is as it should be.

**Comment by dkpat12** [comment]
I've now tested this locally; Looked the same as the live website to me! 

cc: @KevinPayravi  review& merge whenever you are ready 😄

**Review by KevinPayravi — APPROVED** [review]
LGTM

**Comment by KevinPayravi** [comment]
Great update, thank you!

**Pull request merged**
